In [34]:
import pandas as pd
import numpy as np

1. Combine a 1D NumPy array with a 2D NumPy array.
2. Flatten a 2D NumPy array into a 1D array.
3. Reverse the elements of a NumPy array.

In [35]:
a = np.array([1,2,2,4])
b = np.array([[2,3,4,5],[4,5,6,7]])
res = a+b
print(res)

c = np.array([[3,4,5,6],[2,6,8,9]])
# c.reshape(8,)
print(c.flatten())


d = np.array([49,51,73,88,23,74,41])
d1 = d[::-1]
print(d1)

[[ 3  5  6  9]
 [ 5  7  8 11]]
[3 4 5 6 2 6 8 9]
[41 74 23 88 73 51 49]


4. Practice basic NumPy array operations:
-           Find the maximum value in an array.
-           Find the minimum value in an array.
-           Determine the number of rows and columns in an array.
-           Access and select array elements, both individual and specific elements.
-           Calculate the sum of elements in a 2D array using a for loop.
-           Perform addition, subtraction, multiplication, and division on NumPy arrays.

In [36]:
a1 = np.array([23,45, 79, 64, 20])
print(a1)
print(f"Maximum in array is: {a1.max()}")
print("_______________________________")
a2 = np.array([23,45, 79, 64, 20])
print(a2)
print(f"Minimum in array is: {a1.min()}")
print("_______________________________")
a3 = np.array([[3,4,5,6,7],[2,4,6,8,0]])
print(a3)
print(f"No. of rows in array is: {(a3.shape)[0]}")
print(f"No. of columns in array is: {(a3.shape)[1]}")
print("_______________________________")
a4 = np.array([[31,42,53,64,75], [20,42,64,86,50], [51,63,85,47,79]])
print(f"Individual Array element (at 1st row) is: {a4[0]}")
print(f"Specific Array element (in 2nd row and 5th column) is: {a4[1][4]}")
print("_______________________________")
a5 = np.array([[31,22,63,94,25], [27,45,62,81,54], [51,63,85,47,79]])
print(f"Sum of all array elements(without for loop): {a5.sum()}")
row = (a5.shape)[0]
col = (a5.shape)[1]
sum = 0
for a in range(row):
    for b in range(col):
        sum += a5[a][b]
print(f"Sum of all array elements (using for loop): {sum}")
print("_______________________________")
a6 = np.array(range(10, 20, 2))
a7 = np.array(range(20, 40, 4))
print(f"Array 1: {a6}")
print(f"Array 2: {a7}")
print(f"Sum: {a6+a7}")
print(f"Difference: {a6-a7}")
print(f"Product: {a6*a7}")
a7_ = np.array(range(10, 30, 4))
print(f"Division: {(a6/a7_).round(2)}")

[23 45 79 64 20]
Maximum in array is: 79
_______________________________
[23 45 79 64 20]
Minimum in array is: 20
_______________________________
[[3 4 5 6 7]
 [2 4 6 8 0]]
No. of rows in array is: 2
No. of columns in array is: 5
_______________________________
Individual Array element (at 1st row) is: [31 42 53 64 75]
Specific Array element (in 2nd row and 5th column) is: 50
_______________________________
Sum of all array elements(without for loop): 829
Sum of all array elements (using for loop): 829
_______________________________
Array 1: [10 12 14 16 18]
Array 2: [20 24 28 32 36]
Sum: [30 36 42 48 54]
Difference: [-10 -12 -14 -16 -18]
Product: [200 288 392 512 648]
Division: [1.   0.86 0.78 0.73 0.69]


5. Iterate through a 3D NumPy array using:
-       Nested for loops
-       numpy.nditer()

In [37]:
a8 = np.array([[[23,45,67],[32,54,76]],
               [[89,65,34],[28,91,18]],
               [[44,75,90],[34,57,86]]])

print(f"Printing 3D array (using for loop)")

for row in range((a8.shape)[0]):
    for col in range((a8.shape)[1]):
        for depth in range((a8.shape)[2]):
            print(f"Element{[row]}{[col]}{[depth]}: {a8[row][col][depth]}")
print("________________________________________")

print("________________________________________")
print(f"Printing 3D array (using nditer function)")

count = 0
for x in np.nditer(a8):
    count+=1
    print(f"Element[{count}]: {x}")

Printing 3D array (using for loop)
Element[0][0][0]: 23
Element[0][0][1]: 45
Element[0][0][2]: 67
Element[0][1][0]: 32
Element[0][1][1]: 54
Element[0][1][2]: 76
Element[1][0][0]: 89
Element[1][0][1]: 65
Element[1][0][2]: 34
Element[1][1][0]: 28
Element[1][1][1]: 91
Element[1][1][2]: 18
Element[2][0][0]: 44
Element[2][0][1]: 75
Element[2][0][2]: 90
Element[2][1][0]: 34
Element[2][1][1]: 57
Element[2][1][2]: 86
________________________________________
________________________________________
Printing 3D array (using nditer function)
Element[1]: 23
Element[2]: 45
Element[3]: 67
Element[4]: 32
Element[5]: 54
Element[6]: 76
Element[7]: 89
Element[8]: 65
Element[9]: 34
Element[10]: 28
Element[11]: 91
Element[12]: 18
Element[13]: 44
Element[14]: 75
Element[15]: 90
Element[16]: 34
Element[17]: 57
Element[18]: 86


6. Study the following NumPy program and extend it to calculate statistical measures for two 2D arrays:
-       Mean (Average)
-       Median
-       Mode

In [38]:
a9 = np.array([[31,22,44,94,25], [27,99,62,13,54], [51,63,15,47,18]])
a10 = np.array([[30,92,38,94,25], [27,45,37,80,36], [60,63,64,47,80]])

print(f"Array 1: {a9}")
print("___________________________")
print(f"Array 1: {a10}")
print("___________________________")
a11 = np.concatenate((a9.flatten(), a10.flatten()))
print(f"Combined Array: {a11}")
a12 = np.sort(a11)
print(f"Combined & Sorted Array: {a12}")
mean = np.mean(a11)
median = np.median(a11)
values, counts = np.unique(a11, return_counts=True)
mode = values[np.argmax(counts)]

print("Mean:", mean.round(2))
print("Median:", median)
print("Mode:", mode)

Array 1: [[31 22 44 94 25]
 [27 99 62 13 54]
 [51 63 15 47 18]]
___________________________
Array 1: [[30 92 38 94 25]
 [27 45 37 80 36]
 [60 63 64 47 80]]
___________________________
Combined Array: [31 22 44 94 25 27 99 62 13 54 51 63 15 47 18 30 92 38 94 25 27 45 37 80
 36 60 63 64 47 80]
Combined & Sorted Array: [13 15 18 22 25 25 27 27 30 31 36 37 38 44 45 47 47 51 54 60 62 63 63 64
 80 80 92 94 94 99]
Mean: 49.43
Median: 46.0
Mode: 25
