In [108]:
import numpy as np
import pandas as pd

### Create a NumPy array and perform the following operations:
 * Convert a 1D array to a 2D array.
 * Print Array Attributes (like shape, dimension, data type, itemsize).
 * Create a 3x3 NumPy array of all 9s.
 * Create a 1D array of 10 evenly spaced values between 25 and 125.
 * Convert a Python list into a NumPy array.
 * Reverse a 1D NumPy array.
 * Create a 4x4x3 array and extract the value at its second set, first row, and last column.
 * Create a 4x4 array and extract odd rows and even columns.
 * Slice the first two rows and first two columns of the second set from a 4x4x3 array.
 * Replace all odd numbers in a NumPy array with -1 by iterating using a for loop. Use the following array:
   [[23, 56, 78, 93],
    [71, 82, 13, 24]]
   
 * Get the indices of non-zero elements in the array [1, 0, 2, 0, 3, 0, 4].
 * Perform arithmetic operations on two NumPy arrays element-wise:
   * Add two NumPy arrays element by element.
   * Multiply two NumPy arrays element by element.
 * Write code to compute the dot product of two NumPy arrays:
   arr1 = [15, 20, 25]
   arr2 = [10, 40, 37]

In [109]:
a = np.array([1,2,3,4,5,6,8,9,0,1,5,6])
print(f"1D Array: \n{a}")
print("_____________________________")
print(f"Printing different possible 2D arrays for this 1D array: ")
a1 = np.reshape(a, (6,2))
print(f"1.) 2D array(): \n{a1}")
print("_____________________________")
a2 = np.reshape(a, (4,3))
print(f"2.) 2D array: \n{a2}")
print("_____________________________")
a3 = np.reshape(a, (2,6))
print(f"3.) 2D array: \n{a3}")
print("_____________________________")
a4 = np.reshape(a, (3,4))
print(f"4.) 2D array: \n{a4}")

1D Array: 
[1 2 3 4 5 6 8 9 0 1 5 6]
_____________________________
Printing different possible 2D arrays for this 1D array: 
1.) 2D array(): 
[[1 2]
 [3 4]
 [5 6]
 [8 9]
 [0 1]
 [5 6]]
_____________________________
2.) 2D array: 
[[1 2 3]
 [4 5 6]
 [8 9 0]
 [1 5 6]]
_____________________________
3.) 2D array: 
[[1 2 3 4 5 6]
 [8 9 0 1 5 6]]
_____________________________
4.) 2D array: 
[[1 2 3 4]
 [5 6 8 9]
 [0 1 5 6]]


In [110]:
print(f"Shape of array is: {a.shape}")
print(f"Dimension of array is: {a.ndim}")
print(f"Data Type of array is: {a.dtype}")
print(f"Item Size of array is: {a.itemsize}")

Shape of array is: (12,)
Dimension of array is: 1
Data Type of array is: int64
Item Size of array is: 8


In [111]:
arr5 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(f"3D Array: \n{arr5}")
print("________________")
arr6 = np.array(range(25, 125, 10))
print(f"Array in range 25 to 125 evenly spaced by 10: \n{arr6}")
print("________________")
l = [26,37,45,54,63,72,81]
arr6 = np.array(l)
print(f"Array from list: {arr6}")
print("________________")
arr7 = np.array([26,37,45,54,63,72,81])
print(f"Original Array: {arr7}")
print(f"Reverse of this array: {arr7[::-1]}")
print("________________")

3D Array: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
________________
Array in range 25 to 125 evenly spaced by 10: 
[ 25  35  45  55  65  75  85  95 105 115]
________________
Array from list: [26 37 45 54 63 72 81]
________________
Original Array: [26 37 45 54 63 72 81]
Reverse of this array: [81 72 63 54 45 37 26]
________________


In [112]:
arr8 = np.array([
        [[11,20,32],[48,56,68],[11,41,93],[20,65,51]],
        [[13,23,33],[42,52,67],[17,45,97],[27,67,52]],
        [[14,23,34],[47,53,64],[15,46,95],[23,68,53]],     
        [[19,29,38],[46,58,62],[12,48,91],[22,69,54]]        
])
set_ = arr8.shape[0]
rows = arr8.shape[1]
columns = arr8.shape[2]
print(f"Original Array: \n{arr8}")
print(f"Value at second set, first row, last colmun : {arr8[1][0][2]}")
print("_________________________________________________")
print(f"From 2nd set, ")
print(f"First Two Rows are: {arr8[1][0]}, {arr8[1][1]}")
print(f"First Two Columns are: \n{f[1][0][0]}, {f[1][1][0]}, {f[1][2][0]}, {f[1][3][0]} \n{f[1][0][1]}, {f[1][1][1]}, {f[1][2][1]}, {f[1][3][1]}")
print("_________________________________________________")
arr9 = np.array([
            [132,314,586,778],
            [172,374,536,718],
            [192,354,516,748],
            [102,324,506,708]
            ])
print(f"Original Array: \n{arr8}")
row = arr9.shape[0]
column = arr9.shape[1]
print(f"\nOdd Rows: ")
for i in range(row):
    if(i%2==0): print(f"Row {i+1}: {arr9[i]}")
print("\nEven Columns:")
for j in range(column):
    if j % 2 != 0: print(f"Col {j+1}", end="\t")
print()
for i in range(row):
    for j in range(column):
        if j % 2 != 0: print(arr9[i][j], end="\t")
    print()

Original Array: 
[[[11 20 32]
  [48 56 68]
  [11 41 93]
  [20 65 51]]

 [[13 23 33]
  [42 52 67]
  [17 45 97]
  [27 67 52]]

 [[14 23 34]
  [47 53 64]
  [15 46 95]
  [23 68 53]]

 [[19 29 38]
  [46 58 62]
  [12 48 91]
  [22 69 54]]]
Value at second set, first row, last colmun : 33
_________________________________________________
From 2nd set, 
First Two Rows are: [13 23 33], [42 52 67]
First Two Columns are: 
13, 42, 17, 27 
23, 52, 45, 67
_________________________________________________
Original Array: 
[[[11 20 32]
  [48 56 68]
  [11 41 93]
  [20 65 51]]

 [[13 23 33]
  [42 52 67]
  [17 45 97]
  [27 67 52]]

 [[14 23 34]
  [47 53 64]
  [15 46 95]
  [23 68 53]]

 [[19 29 38]
  [46 58 62]
  [12 48 91]
  [22 69 54]]]

Odd Rows: 
Row 1: [132 314 586 778]
Row 3: [192 354 516 748]

Even Columns:
Col 2	Col 4	
314	778	
374	718	
354	748	
324	708	


In [113]:
arr9 = np.array([[23,56,78,93],[71,82,13,24]])
row_arr9=arr9.shape[0]
col_arr9=arr9.shape[1]
print(f"Original Array: \n{arr9}")
for i in range(row_arr9):
    for j in range(col_arr9):
        if((arr9[i][j]%2)!=0): arr9[i][j]=-1
print(f"Modified Array: \n{arr9}")
print(":::::::::::::::::")
arr10 = np.array([1,0,2,0,3,0,4])
print(f"Original Array: \n{arr10}")
print("Non-Zero elements are at indexes:", end=" ")
for i in range(len(arr10)):
    if(arr10[i]): print(i, end=", ")

Original Array: 
[[23 56 78 93]
 [71 82 13 24]]
Modified Array: 
[[-1 56 78 -1]
 [-1 82 -1 24]]
:::::::::::::::::
Original Array: 
[1 0 2 0 3 0 4]
Non-Zero elements are at indexes: 0, 2, 4, 6, 

In [114]:
arr11 = np.array([12,34,56,87,65,43])
arr12 = np.array([21,32,53,68,90,74])
sum_arr = arr11+arr12
print(f"Sum array is {sum_arr}")
prod_arr= arr11*arr12
print(f"Product array is {prod_arr}")
print("_______________________________")
arr13 = np.array([15,20,25])
arr14 = np.array([10,40,37])
dot_=arr13.dot(arr14)
print(f"Dot Product is {dot_}")

Sum array is [ 33  66 109 155 155 117]
Product array is [ 252 1088 2968 5916 5850 3182]
_______________________________
Dot Product is 1875
