1) Replace Nan with 0 and Interchange 3 rows and 3 columns of 2D array [[6, -8, 73, -110], [np.nan, -8, 0, 94]] 
2) Move axes of 3D array to new positions 
3) Replace NaN values with average of columns 
4) Replace negative value with zero in numpy array using replace

In [7]:
import numpy as np

arr = np.array([[6, -8, 73, -110], [np.nan, -8, 0, 94]])
print(arr)
print("____________________________")
arr1 = np.nan_to_num(arr, nan=0.0)
print(arr1)


#Interchanging the columns
arr[[0, 1]] = arr[[1, 0]]
arr[:, [2, 3]] = arr[:, [3, 2]]

[[   6.   -8.   73. -110.]
 [  nan   -8.    0.   94.]]
____________________________
[[   6.   -8.   73. -110.]
 [   0.   -8.    0.   94.]]


In [11]:
arr2 = np.random.randint(0, 100, size=(2, 3, 4))
print(arr2.shape)

# change axes
arr4 = np.moveaxis(arr2, [0, 1, 2], [1, 2, 0])
#arr4 = np.transpose(arr2, (1,2,0))
print(arr4.shape)

(2, 3, 4)
(4, 2, 3)


In [16]:
arr5 = np.array([[1.0, 2.0, np.nan],
                [4.0, np.nan, 6.0],
                [7.0, 8.0, 9.0]])
print(arr5)          

col_means = np.nanmean(arr5, axis=0)
for i in range(arr5.shape[1]):
    arr5[:, i] = np.where(np.isnan(arr5[:, i]), col_means[i], arr5[:, i])
print("_________________")
print(arr5)


[[ 1.  2. nan]
 [ 4. nan  6.]
 [ 7.  8.  9.]]
_________________
[[1.  2.  7.5]
 [4.  5.  6. ]
 [7.  8.  9. ]]


In [20]:
arr6 = np.array([[6, -8, 73, -110],
                [-5, -8, 0, 94],
                [2, -3, 10, -1]])
print(arr6)
arr6 = np.where(arr6 < 0, 0, arr6)
print("_________________________")
print(arr6)

[[   6   -8   73 -110]
 [  -5   -8    0   94]
 [   2   -3   10   -1]]
_________________________
[[ 6  0 73  0]
 [ 0  0  0 94]
 [ 2  0 10  0]]
